### ISSUE TITLE
Conversion of TSLint semicolon rule seems incorrect?

### ISSUE THREAD

**Issue by rich-newman** [typescript-eslint/tslint-to-eslint-config#1207]
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.9.2 (latest)
-   ESLint version: Not installed
-   Node version: 14.17.5

#### Actual Behavior

Migration of the TSLint `semicolon` rule enables ESLint's `semi` rule as well as `@typescript-eslint/semi`.  This seems to be [contrary to the docs for @typescript-eslint/semi](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/semi.md), and leads to two errors reported for one missing semicolon when we lint with ESLint.

#### Expected Behavior

ESLint's `semi` rule should be `off`?  I'm a little unsure if it is being set to `error` deliberately for some reason?

#### Reproduction

- Create tslint.json in a folder as below:
```
{
  "rules": {
    "semicolon": [ true, "always" ]
  }
}
```
- In the folder, install and run the converter: `npm i tslint-to-eslint-config`, `npx tslint-to-eslint-config`
- Resulting .eslintrc.js is below.  
```
module.exports = {
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "tsconfig.json",
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "@typescript-eslint/member-delimiter-style": [
            "error",
            {
                "multiline": {
                    "delimiter": "semi",
                    "requireLast": true
                },
                "singleline": {
                    "delimiter": "semi",
                    "requireLast": false
                }
            }
        ],
        "@typescript-eslint/semi": [
            "error",
            "always"
        ],
        "semi": "error"
    }
};
```

**Comment by JoshuaKGoldberg** [comment]
Hmm, very weird! In the `semicolon` converter it specifically sets `semi` to `ruleSeverity: "off"`:

https://github.com/typescript-eslint/tslint-to-eslint-config/blob/4a8adeadf42cce39d5f1169e9cbec8eee810e635/src/converters/lintConfigs/rules/ruleConverters/semicolon.ts#L20

Something is spooky and should be fixed. Thanks for filing @rich-newman!

**Comment by JamesHenry** [comment]
I'm afraid this isn't fixed! I will open a new issue with a minimal reproduction
